vitorgalvao/tiny-scripts

cask-repair

Without ,? the url incorporates the terminal comma should it exist.  Basically means the sha will be wrong, and in different ways depending on how the url is redirected.  Refs #4

Reintroduce regex to fix appcast_url parsing

---

cask-repair

If you configure you environment with a GITHUB_TOKEN environment variable, then hub will use it instead (it appears...since I'm able to run hub issues just fine - it doesn't even ask me to log in or anything)
However, the first check of cask-repair requires that a token be stored in ~/.config/hub. I would suggest that if the environment variable GITHUB_TOKEN is set, that the script also treats hub as "configured".
This PR fixes issue #21

Also check if the GITHUB_TOKEN environment variable is set

---

fastmerge
prfixmaster

Emulate GitHub's behavior when squash-merging a PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitorgalvao/tiny-scripts/25)

fastmerge, prfixmaster: Add issue number to commit message header

---

fastmerge
prfixmaster

This introduces a dependency on GNU's `sed`, as I couldn't get the BSD version to work. The `prfixmaster` and `fastmerge` formulae will each need a `depends_on "gnu-sed"`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitorgalvao/tiny-scripts/28)

prfixmaster, fastmerge: squash commits into one before pushing

---

cask-repair

The recent change (https://github.com/vitorgalvao/tiny-scripts/commit/1614d268406ec4d5355cec7f870b5cf17e9c6771)  gives me following error message:
```
curl: option --user_agent: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```
The [manpage](https://curl.haxx.se/docs/manpage.html#-A) also states  this should be `--user-agent` instead of `--user_agent`.
(curl version 7.43.0)

Fix curl user-agent option

---

cask-repair

`EDITOR` can be set with arguments (e.g. `subl -n -w`), in which case directly applying it in quotes results in a "file not found" error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitorgalvao/tiny-scripts/31)

cask-repair: use eval with EDITOR

---

cask-repair

See https://github.com/vitorgalvao/tiny-scripts/issues/26#issuecomment-234400952
Avoid failures when setting upstream branch by using `remote/branch` instead of just `remote.`

Include branch name when specifying upstream

---

prfixbranch
prfixmaster

This way we can avoid manually editing `.git/rebase-apply/patch` and dealing with weird `git am` errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitorgalvao/tiny-scripts/34)

prfix*: fall back on 3-way merge if patch does not apply cleanly

---

fastmerge
prfixbranch
prfixmaster

Instead of using the `--remote` flag every time if it's different from the default (`upstream`), just `git config tiny-scripts.remote {{remote}}`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitorgalvao/tiny-scripts/35)

fastmerge, prfix*: add tiny-scripts.remote config

---

prfixbranch
prfixmaster

This recently bit me in https://github.com/caskroom/homebrew-cask/pull/23603.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitorgalvao/tiny-scripts/36)

prfix*: Exclude untracked files from uncommitted changes

---

cask-repair

macOS sed adds a LF to end of blob before passing to shasum. If a copy of GNU sed exists in the path, resulting blob does not have LF, so sha256 will mismatch. See [here](https://stackoverflow.com/questions/13325138/why-does-sed-add-a-new-line-in-osx) for more information.

Make sure system copy of sed is used

---

cask-repair

Revamp of `cask-repair`, with some important changes:
+ [Way easier to setup and use](https://github.com/caskroom/homebrew-cask/pull/29079):
+ No longer needs any manual forking or setting of remotes.
+ No need to fiddle with `--push|-p` and `--pull|-l` flags (they were deprecated).
+ No longer need to be inside a `homebrew-*/Casks` repo. Works from anywhere.
+ You can now give multiple cask arguments at once.
+ You can now give `s` as the version to skip a cask.
+ Added `--install` flag to install updated cask right after submitting PR.
+ Auto-skip casks with `language`.
+ Introduces new method of `appcast`-checking (https://github.com/caskroom/homebrew-cask/pull/28966).
+ Fixes bugs (and may introduce others).
A few relevant implementation details (the script will visibly warn you with …

cask-repair revamp

---

cask-repair

I think this will display correctly (tested echoing in terminal) but I'm not familiar with CLI git/hub so I haven't been able to successfully test it with a PR.

cask-repair - add sha256 confirm to match cask PR template

---

cask-repair

I forgot to change the brackets for the `sha256.md` URL. Should be `( )` not `[ ]`.

cask-repair - fix template brackets

---

cask-repair

This pull request addresses issues raised in #85 and #86 while taking into consideration challenges presented in #61 and #57. The goal is to support both git and https protocols and use by default what the user has configured with hub.
With this change cask-repair avoids setting user configurable preferences either in the local repository with `git config --local hub.protocol https` or globally with `git config --global hub.protocol https` and does not enforce a custom remote name for the user's fork.
A simple `hub fork` is now used to create both the fork and the remote. Checks are still performed to ensure the remote is present based on the known default remote name. Branch names are no longer based on the remote name and instead use a cask_repair_branch_prefix followed by a hyphen and …

cask-repair: use hub default remote & protocol with custom branch prefix

---

cask-repair

Changes `[version-checksum]` to a URL.

cask-repair: update PR template

---

cask-repair

Currently this also deletes `homebrew-core` branches.

cask-repair: only prune cask branches

---

cask-repair

For a first-time user, this instruction leaves them in
`/usr/local/Homebrew` unexpectedly. Everything works fine... it's just
weird.
The only important think about being in `brew --repository` is that it
is known to be a gitlab repo, so it's a good, confident bet, fine to
keep using.
But by running this in a subshell, it will keep the user in their
existing directory

Stay in cask repo when repairing

---

cask-analytics

@brianmorton @core-code Heads-up, as you might be interested in this script which I’ve been using for quick checks (`brew install vitorgalvao/tiny-scripts/cask-analytics`). Example usage:
```
$ cask-analytics alfred
alfred (added 837 days ago)
30 days: 3,483 (#29)
90 days: 9,186 (#33)
365 days: 20,462 (#30)
```
This PR adds a `-a, --no-age` flag, which suppresses the ` (added 837 days ago)`. Checking the age is slow (because it uses `git log`), but useful (to check if a cask has poor analytics because it was added recently).

cask-analytics: option to not show age

---

cask-repair

When I use cask-repair and need to amend the PR with additional changes, I often checkout the automatically created branch locally but forget to checkout master afterwards. Subsequently repairing a cask then creates a new branch off of the branch I used to make the changes, instead of the master branch. In such cases, the PR then contains the previous cask repair as well.
This PR fixes this issue by ensuring we always branch off of the master branch.
Potential extensions:
- Remember which branch we come from, and checkout that branch again after the repair.
*I'm not sure whether this is a good idea, since then I might get stuck on a custom branch without knowing and not receive updates for multiple days.*
- Automatically stash uncommitted changes before checking out the new branch, and …

cask-repair: Ensure we branch off of master

---

cask-repair

When not bumping a version, `cask-repair` defaults to `Update {cask}` as commit message. Previously, if we wanted to change the commit message, we'd need to let `cask-repair` submit the PR, rebase and force-push the commit, and optionally change the PR title.
This PR adds the `-r | --reword` flag which, if given, lets the user manually reword the commit message before committing and pushing. The default message is filled in advance, and after the edit, the commit's first line is extracted as the new PR title.
Exemplified in Homebrew/homebrew-cask-versions#8126

cask-repair: Add option to reword commit message

---

cask-repair

Use `brew reinstall` instead of `brew cask reinstall` since the
latter is now deprecated.

cask-repair: use brew reinstall

---

cask-repair

Fixes https://github.com/vitorgalvao/tiny-scripts/issues/196
`brew cask fetch` returns color output which causes `sed` not to strip the redundant text correctly in certain environment (specifically, in my case, GitHub Actions). This fixes the bug by simply setting `brew cask fetch` to return the plain text output (Ref: https://github.com/Homebrew/brew/pull/3090/files).

cask-repair: fix download file path is not retrieved correctly

---

cask-repair

Noticed the following when running `cask-repair`, just now:
```
Warning: Calling brew cask fetch is deprecated! Use brew fetch [--cask] instead.
```
Not sure if this wasn't changed because it breaks something or if it had simply yet to be done.
Either way, here's a PR, just in case! 👍🏻

Update `brew cask fetch` to `brew fetch --cask`

---

cask-repair

When switched from `brew cask fetch` to `brew fetch --cask` in #201  output is changed and is now printing sha256 as last line. This fixes sha256 calculation.
Previously this following error;
```
• audit for loopback: failed
- sha256 string must be of 64 hexadecimal characters
```
Because of `brew cask fetch` command outputs;
```
ykursadkaya@YKKs-MacBook-Air: ~% brew cask fetch cyberduck
Warning: Calling brew cask fetch is deprecated! Use brew fetch [--cask] instead.
==> Downloading external files for Cask cyberduck
==> Downloading https://update.cyberduck.io/Cyberduck-7.7.2.33862.zip
Already downloaded: /Users/ykursadkaya/Library/Caches/Homebrew/downloads/f09cc72c465cbf599635002ca568ce633f1c01733f0926de7122b6735931c5a0--Cyberduck-7.7.2.33862.zip
==> Success! Downloaded to -> …
```

cask-repair fix package_sha for brew fetch output

---

cask-repair

those are almost always false positive and prevent sending from muUpdateStaticHomebrewCask

don't ask about on non-200 http codes on blind-submits
